create table products (
	id INT,
	name VARCHAR(50),
	description VARCHAR(50),
	price VARCHAR(50),
	category VARCHAR(50),
	color VARCHAR(50),
	mark VARCHAR(50),
	size VARCHAR(50),
	stock INT,
	delivery VARCHAR(50)
);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (1, 'Nevile', 'Other specified crystal arthropathies, right knee', '$6.01', 'Home', 'Teal', 'Ardmore Shipping Corporation', '2XL', 18, false);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (2, 'Theressa', 'Accessory nipple', '$2.02', 'Computers', 'Puce', 'Cleantech Solutions International, Inc.', '3XL', 86, true);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (3, 'Charyl', 'Myositis ossificans progressiva, forearm', '$3.94', 'Outdoors', 'Indigo', 'FLIR Systems, Inc.', 'M', 4, true);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (4, 'Milicent', 'Trigger finger, left middle finger', '$4.73', 'Sports', 'Yellow', 'National Storage Affiliates Trust', 'M', 4, true);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (5, 'Corbet', 'Fracture of ramus of left mandible, subsequent encounter for fracture with routine healing', '$2.54', 'Home', 'Goldenrod', 'First United Corporation', 'M', 57, true);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (6, 'Sianna', 'Congenital leukonychia', '$2.07', 'Health', 'Khaki', 'Kayne Anderson MLP Investment Company', 'S', 10, true);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (7, 'Sarette', 'Encounter for testing of male partner of patient with recurrent pregnancy loss', '$3.79', 'Jewelery', 'Khaki', 'NASDAQ TEST STOCK', 'XS', 58, false);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (8, 'Krispin', 'Unspecified superficial injury of unspecified hip, subsequent encounter', '$9.38', 'Electronics', 'Maroon', 'Dataram Corporation', '2XL', 75, true);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (9, 'Sibilla', 'Displaced fracture of cuboid bone of right foot, subsequent encounter for fracture with nonunion', '$9.01', 'Movies', 'Turquoise', 'Teleflex Incorporated', 'L', 81, false);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (10, 'Sapphire', 'Salter-Harris Type I physeal fracture of right calcaneus, subsequent encounter for fracture with malunion', '$7.53', 'Beauty', 'Aquamarine', 'Nuveen Municipal Credit Income Fund', 'M', 11, false);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (11, 'Gay', 'Unspecified macular degeneration', '$9.27', 'Baby', 'Blue', 'Federal Realty Investment Trust', 'M', 46, false);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (12, 'Eloise', 'Poisoning by antineoplastic and immunosuppressive drugs, undetermined, initial encounter', '$3.60', 'Electronics', 'Khaki', 'Corporate Office Properties Trust', 'L', 34, false);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (13, 'Erinn', 'Supervision of elderly primigravida', '$1.28', 'Home', 'Red', 'iShares MSCI Europe Small-Cap ETF', 'L', 66, false);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (14, 'Jewel', 'Leucocoria, left eye', '$0.98', 'Books', 'Orange', 'Dollar Tree, Inc.', 'XS', 59, true);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (15, 'Allsun', 'Other calcification of muscle, shoulder', '$6.25', 'Movies', 'Violet', 'Comstock Holding Companies, Inc.', 'XL', 7, false);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (16, 'Thedric', 'Toxic effect of dichloromethane, intentional self-harm, subsequent encounter', '$8.04', 'Toys', 'Teal', 'Blackrock Capital and Income Strategies Fund Inc', 'L', 44, true);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (17, 'Kally', 'Spontaneous rupture of extensor tendons, shoulder', '$1.34', 'Garden', 'Red', 'Pangaea Logistics Solutions Ltd.', 'XS', 26, false);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (18, 'Erich', 'Encounter for fertility preservation counseling', '$0.69', 'Toys', 'Turquoise', 'The Gabelli Healthcare & Wellness Trust', '3XL', 39, true);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (19, 'Menard', 'Laceration without foreign body of abdominal wall, left upper quadrant with penetration into peritoneal cavity, sequela', '$7.23', 'Kids', 'Pink', 'Public Storage', '3XL', 60, true);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (20, 'Daryle', 'Acquired deformity of musculoskeletal system, unspecified', '$3.57', 'Tools', 'Pink', 'Sigma Labs, Inc.', 'S', 85, false);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (21, 'Foss', 'Struck by field hockey puck, initial encounter', '$8.65', 'Computers', 'Green', 'S&W Seed Company', 'XL', 12, false);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (22, 'Lovell', 'Displaced fracture of distal phalanx of left index finger, subsequent encounter for fracture with nonunion', '$8.13', 'Grocery', 'Teal', 'Rite Aid Corporation', '3XL', 75, true);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (23, 'Cordie', 'Laceration of heart with hemopericardium', '$6.77', 'Music', 'Turquoise', 'Frankly, Inc.', 'XL', 56, false);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (24, 'Silvan', 'General hospital and personal-use devices associated with adverse incidents', '$9.29', 'Home', 'Teal', 'Sotherly Hotels Inc.', '2XL', 80, false);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (25, 'Jeremie', 'Displaced fracture of distal phalanx of right index finger', '$3.54', 'Outdoors', 'Blue', 'International Seaways, Inc.', '2XL', 84, true);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (26, 'Wren', 'Displaced fracture of medial phalanx of unspecified finger', '$6.93', 'Jewelery', 'Mauv', 'Interstate Power and Light Company', '3XL', 93, false);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (27, 'Jenilee', 'Hit or struck by falling object due to accident to (nonpowered) inflatable craft, subsequent encounter', '$7.76', 'Movies', 'Maroon', 'Vornado Realty Trust', '3XL', 2, false);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (28, 'Grantham', 'Quadriplegia, C1-C4 complete', '$6.68', 'Computers', 'Teal', 'UGI Corporation', 'S', 71, false);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (29, 'August', 'Other osteonecrosis, humerus', '$9.25', 'Electronics', 'Orange', 'CHF Solutions, Inc.', 'XL', 11, true);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (30, 'Barbara', 'Traumatic subarachnoid hemorrhage with loss of consciousness of any duration with death due to brain injury prior to regaining consciousness, sequela', '$2.00', 'Garden', 'Fuscia', 'Lipocine Inc.', 'S', 53, false);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (31, 'La verne', 'Underdosing of other drugs acting on muscles, sequela', '$5.76', 'Baby', 'Yellow', 'Allegiance Bancshares, Inc.', '3XL', 5, true);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (32, 'Clemmie', 'Poisoning by smallpox vaccines, assault, subsequent encounter', '$8.54', 'Books', 'Orange', 'Medtronic plc', 'XS', 90, false);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (33, 'Chaddie', 'Intentional self-harm by unspecified sharp object, subsequent encounter', '$8.61', 'Books', 'Violet', 'IntriCon Corporation', 'M', 43, true);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (34, 'Virge', 'External constriction, left lower leg', '$2.40', 'Automotive', 'Purple', 'Drive Shack Inc.', 'XL', 88, false);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (35, 'Miguela', 'Crushing injury of unspecified part(s) of right wrist, hand and fingers, sequela', '$5.20', 'Computers', 'Teal', 'Horizon Bancorp (IN)', 'XS', 93, false);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (36, 'Konstantine', 'Other multiple births, some liveborn', '$2.03', 'Grocery', 'Blue', 'European Equity Fund, Inc. (The)', '3XL', 31, true);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (37, 'Linzy', 'Military operations involving explosion of improvised explosive device [IED], military personnel', '$2.46', 'Industrial', 'Maroon', 'National Bankshares, Inc.', 'S', 32, true);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (38, 'Papagena', 'Laceration with foreign body of right ear, sequela', '$2.20', 'Kids', 'Turquoise', 'Superior Uniform Group, Inc.', '2XL', 6, true);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (39, 'Sinclare', 'Toxic effect of contact with unspecified venomous animal, intentional self-harm', '$3.23', 'Outdoors', 'Fuscia', 'Momo Inc.', '2XL', 84, true);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (40, 'Ethyl', 'Poisoning by other systemic antibiotics, intentional self-harm', '$0.70', 'Automotive', 'Crimson', 'Blackrock MuniHoldings Fund II, Inc.', 'M', 81, true);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (41, 'Daffy', 'Puncture wound without foreign body of unspecified ear, sequela', '$4.48', 'Clothing', 'Mauv', 'KKR Financial Holdings LLC', '3XL', 96, false);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (42, 'Leticia', 'Other superficial bite of unspecified thumb, initial encounter', '$7.72', 'Garden', 'Puce', 'Insight Select Income Fund', 'XS', 85, false);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (43, 'Camilla', 'Other injury of other muscle(s) and tendon(s) at lower leg level, right leg', '$7.84', 'Beauty', 'Crimson', 'Mellanox Technologies, Ltd.', 'XL', 9, true);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (44, 'Marylou', 'Nondisplaced fracture of unspecified tibial spine, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with malunion', '$0.57', 'Home', 'Crimson', 'Blackrock New York Municipal Income Quality Trust', '3XL', 82, true);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (45, 'Melina', 'Abnormal level of other drugs, medicaments and biological substances in specimens from female genital organs', '$4.67', 'Automotive', 'Pink', 'First Business Financial Services, Inc.', 'L', 36, true);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (46, 'Piper', 'Abrasion of scrotum and testes, initial encounter', '$6.98', 'Jewelery', 'Teal', 'First Industrial Realty Trust, Inc.', '3XL', 10, false);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (47, 'Bab', 'Burn of first degree of right axilla, subsequent encounter', '$0.87', 'Electronics', 'Indigo', 'Davis Select Worldwide ETF', '2XL', 2, false);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (48, 'Papageno', 'Age-related osteoporosis with current pathological fracture, right humerus, subsequent encounter for fracture with routine healing', '$5.58', 'Health', 'Violet', 'Foresight Autonomous Holdings Ltd.', 'XS', 40, true);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (49, 'Guillaume', 'Food in bronchus causing other injury', '$2.57', 'Tools', 'Crimson', 'ENDRA Life Sciences Inc.', '2XL', 5, false);
insert into products (id, name, description, price, category, color, mark, size, stock, delivery) values (50, 'Emalia', 'Minimal atrophy of maxilla', '$5.05', 'Outdoors', 'Khaki', 'Civista Bancshares, Inc. ', 'L', 68, true);
